const styles = ({ screenWidth }) => {
    return {
        tableContainer: {
            width: screenWidth,
            justifyContent: 'flex-start',
            alignItems: 'flex-start',
            marginTop: 8,
        },
        tableTitle: {
            paddingLeft: 18,
            paddingVertical: 16,
        },
        tableItemsContainer: {
            width: '100%',
        },
        tableScrollView: {
            flex: 1,
        },
        scrollViewContainer: {
            flex: 1,
        },
        scrollView: {
            flex: 1,
        },
        scrollViewContentContainer: {
            paddingBottom: 48,
        },
        row: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            paddingVertical: 12,
            paddingLeft: 14,
            borderBottomWidth: 1,
            borderBottomColor: '#F0F0F0',
        },
        eventHeaderRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.64,
        },
        eventRowImage: {
            width: screenWidth * 0.12,
            height: 37,
            borderRadius: 10,
            overflow: 'hidden',
            marginRight: 12,
        },
        headerRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            backgroundColor: '#F0F0F0',
            backgroundColor: '#F0F0F0',
            paddingVertical: 12,
            paddingLeft: 14,
        },
        row: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            paddingVertical: 12,
            paddingLeft: 14,
            borderBottomWidth: 1,
            borderBottomColor: '#F0F0F0',
        },
        eventHeaderRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.64,
        },
        eventRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.64,
            paddingRight: 18,
        },
        eventRowImage: {
            width: screenWidth * 0.12,
            height: 37,
            borderRadius: 10,
            overflow: 'hidden',
            marginRight: 12,
        },
        hostRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.5,
        },
        headerRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            backgroundColor: '#F0F0F0',
            backgroundColor: '#F0F0F0',
            paddingVertical: 12,
            paddingLeft: 14,
        },
        row: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'flex-start',
            paddingVertical: 12,
            paddingLeft: 14,
            borderBottomWidth: 1,
            borderBottomColor: '#F0F0F0',
        },
        eventHeaderRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.64,
        },
        eventRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.64,
            paddingRight: 18,
        },
        eventRowImage: {
            width: screenWidth * 0.12,
            height: 37,
            borderRadius: 10,
            overflow: 'hidden',
            marginRight: 12,
        },
        hostRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.5,
        },
        dateTimeRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.58,
        },
        attendingRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.4,
        },
        generalTicketsSoldRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.6,
        },
        vipTicketsSoldRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.5,
        },
        grossSalesRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.4,
        },
        actionsRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.6,
        },
        attendeeActionsRow: {
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
            width: screenWidth * 0.6,
        },
        loadMoreContainer: {
            width: screenWidth,
            paddingVertical: 18,
            alignItems: 'center',
            justifyContent: 'center',
        },
    };
};

export default styles;
